<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Tavi.Infrastructure.Persistence</RootNamespace>
    <AssemblyName>Tavi.Infrastructure.Persistence</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Tavi.Abstractions\Tavi.Abstractions.csproj" />
    <ProjectReference Include="..\Tavi.Application\Tavi.Application.csproj" />
    <ProjectReference Include="..\Tavi.Domain\Tavi.Domain.csproj" />
  </ItemGroup>
</Project>
