<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Tavi.Runtime</RootNamespace>
    <AssemblyName>Tavi.Runtime</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Tavi.Application\Tavi.Application.csproj" />
    <ProjectReference Include="..\Tavi.Domain\Tavi.Domain.csproj" />
    <ProjectReference Include="..\Tavi.Extensibility\Tavi.Extensibility.csproj" />
    <ProjectReference Include="..\Tavi.Infrastructure.OpenAI\Tavi.Infrastructure.OpenAI.csproj" />
    <ProjectReference Include="..\Tavi.Infrastructure.Persistence\Tavi.Infrastructure.Persistence.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" />
  </ItemGroup>
</Project>
