<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Tavi.Application</RootNamespace>
    <AssemblyName>Tavi.Application</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Tavi.Abstractions\Tavi.Abstractions.csproj" />
    <ProjectReference Include="..\Tavi.Domain\Tavi.Domain.csproj" />
    <PackageReference Include="System.Memory.Data" />
  </ItemGroup>
</Project>
